import turtle as tur
import colorsys as cs

def draw_letter(letter, gradient_colors):
    if letter == 'w':
        tur.right(30)
        for i in range(4):
            tur.color(gradient_colors[i % len(gradient_colors)])
            tur.begin_fill()
            tur.forward(100)
            tur.left(120)
        tur.end_fill()
        tur.penup()
        tur.right(30)
        tur.forward(100)
        tur.left(120)
        tur.forward(100)
        tur.right(150)
        tur.forward(100)
        tur.left(120)
        tur.forward(100)
        tur.right(150)
        tur.penup()
        tur.forward(70)
    elif letter == 'a':
        tur.right(90)
        for i in range(3):
            tur.color(gradient_colors[i % len(gradient_colors)])
            tur.begin_fill()
            tur.forward(100)
            tur.right(120)
        tur.end_fill()
        tur.penup()
        tur.backward(50)
        tur.left(90)
        tur.pendown()
        tur.forward(50)
        tur.penup()
        tur.backward(50)
        tur.left(90)
        tur.pendown()
        tur.forward(50)
        tur.penup()
        tur.backward(50)
        tur.right(90)
        tur.forward(50)
    elif letter == 'q':
        tur.penup()
        tur.forward(50)
        tur.right(90)
        tur.pendown()
        tur.color(gradient_colors[0])
        tur.begin_fill()
        tur.circle(-50, 180)
        tur.forward(100)
        tur.end_fill()
        tur.penup()
        tur.backward(50)
        tur.left(90)
        tur.forward(40)
        tur.pendown()
        tur.left(90)
        tur.forward(40)
    elif letter == 's':
        for i in range(2):
            tur.color(gradient_colors[i % len(gradient_colors)])
            tur.begin_fill()
            tur.forward(100)
            tur.circle(-50, 180)
            tur.forward(100)
            tur.left(180)
        tur.end_fill()
        tur.penup()
        tur.left(90)
        tur.forward(120)
        tur.left(90)
        tur.pendown()
    elif letter == 'k':
        tur.right(90)
        tur.color(gradient_colors[0])
        tur.begin_fill()
        tur.forward(100)
        tur.backward(50)
        tur.right(45)
        tur.forward(70)
        tur.backward(70)
        tur.right(90)
        tur.forward(70)
        tur.backward(70)
        tur.right(45)
        tur.forward(50)
        tur.end_fill()
        tur.penup()
        tur.backward(100)
        tur.left(90)
        tur.forward(50)
        tur.left(90)
        tur.pendown()
    elif letter == 'h':
        for i in range(2):
            tur.color(gradient_colors[i % len(gradient_colors)])
            tur.begin_fill()
            tur.right(90)
            tur.forward(100)
            tur.backward(50)
            tur.right(90)
            tur.forward(50)
            tur.right(90)
            tur.forward(50)
            tur.backward(100)
            tur.end_fill()
            tur.penup()
            tur.right(90)
            tur.forward(50)
            tur.right(90)
            tur.forward(50)
            tur.left(90)
            tur.pendown()

tur.setup(800, 800)
tur.speed(0)
tur.width(2)
tur.bgcolor("black")

# Define gradient colors
gradient_colors = [cs.hsv_to_rgb(i/15, 1, 1) for i in range(15)]

name = "waqas khan"
for letter in name:
    draw_letter(letter, gradient_colors)
    tur.penup()
    tur.forward(20)
    tur.pendown()

tur.hideturtle()
tur.done()
